@domain=localhost
@port=3000
@host={{domain}}:{{port}}
@pref=http://{{host}}/api

@baseModule = {{pref}}/tokens

### create module
PUT {{baseModule}}
Content-Type: application/json

{
  "type": "blm",
  "write": [],
  "read": [],
  "oldToken": null
}