@baseModules=http://localhost:3000/api/modules
@token=blm-9-R--W--601008

### Upsert module
PUT {{baseModules}}
Content-Type: application/json

{
    "token": "{{token}}",
    "title": "Simple Clock",
    "description": "A clock to show time.",
    "html": "<script src='https://cdn.tailwindcss.com'></script><p class='text-5xl main-time-div'></p>",
    "css": "body {width: 100dvw;height: 100dvh;display: flex;flex-direction: column;justify-content: center;align-items: center;}",
    "js": "const el = document.querySelector('.main-time-div'); function setTime() {const now = new Date(Date.now()); el.innerHTML = `${now.getHours()}:${now.getMinutes()}:${now.getSeconds()}`;};setInterval(setTime, 200);"
}


### delete module
DELETE {{baseModules}}/{{token}}


### publish modules
PUT {{baseModules}}/publish
Content-Type: application/json

{
   "token": "{{token}}"
}


### unpublish modules
PUT {{baseModules}}/unpublish
Content-Type: application/json

{
  "token": "{{token}}"
}




















### get published modules
GET {{baseModules}}


### install plugin
PUT {{baseModules}}/6/1


### uninstall plugin
DELETE {{baseModules}}/6/1


### get installed plugins
GET {{baseModules}}/1





"description": "A clock at your watch.",