@domain=localhost
@port=3000
@host={{domain}}:{{port}}
@pref=http://{{host}}/api

@baseUsers = {{pref}}/users

### get aet
POST {{baseUsers}}/login
Content-Type: application/json

{
  "username": "yanni"
}