@baseAets = {{host}}/api/aet

### get all AETs
GET {{baseAets}}

### edit AET
PUT {{baseAets}}/32
Content-Type: application/json

{
    "title": "Do something else",
    "description": "",
    "date": "2024-03-05T23:00:00.000Z",
    "startTime": 20,
    "endTime": 21,
    "type": "event",
    "color": "#bbcc3a"
}

### delete AET
DELETE {{baseAets}}/32

### add AET
POST {{baseAets}}/
Content-Type: application/json

{
  "title": "Do something important",
  "description": "",
  "date": "2024-03-05T23:00:00.000Z",
  "startTime": 20,
  "endTime": 21,
  "type": "event",
  "color": "#bbcc3a",
  "calenderId": 2
}